# action.yml
name: 'Pandoc convert'

description: 'Convert HTML page to Markdown'

inputs:
  dest:
    description: 'Destination filename'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dest }}
